version: '3'

services:
###> doctrine/doctrine-bundle ###
  psql:
    ports:
      - "54321:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
